env: "local"
server:
  port: ":8002"
token:
  access_ttl: 1h
  refresh_ttl: 24h
  access_key: "basic_key"
  refresh_key: "super_mega_key"
postgres:
  user: "postgres"
  pass: "root"
  port: "8092"
  host: "localhost"
  name: "pets"
  reload: false