env: "local"
server:
  port: ":8003"
postgres:
  user: "postgres"
  pass: "root"
  port: "5432"
  host: "localhost"
  name: "pets"
  reload: false
external:
  enricht: "localhost:8004"
  rabbit:  "localhost:5672"