env: "local"
server:
  port: ":8003"
postgres:
  user: "postgres"
  pass: "root"
  port: "5432"
  host: "postgresql"
  name: "pets"
  reload: false
external:
  enricht: "enricht:8004"
  rabbit: "rabbitmq:15672"